// Cargo.toml
[package]
name = "forensic-triage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
rayon = "1.7"
indicatif = "0.17"
log = "0.4"
chrono = "0.4"
regex = "1.0"